In [1]:
import numpy as np
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
ans1 = np.arange(21)
#2.呈上題，將以上數列取出偶數。
ans2 = ans1[:21:2]  
#3.呈1題，將數列取出3的倍數。
ans3 = ans1[:21:3]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [ 0  2  4  6  8 10 12 14 16 18 20] [ 0  3  6  9 12 15 18]


In [ ]:
#4.請問下列兩種將 Array 轉換成 List 的方式有何不同？
#print('list(a): ', list(a))
#print('tolist(): ', a.tolist())
# list(a)只能將第一層元素轉為list，a.tolist()才能將多層元素轉為list

In [3]:
#5. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 


print(a.ndim) #a陣列只有一個軸
print(a.shape) #a陣列的形狀為6X1
print(a.size) #a陣列有6個元素
print(a.dtype) #a陣列的資料型態
print(a.itemsize) #a陣列每個元素的記憶體使用量
print(len(a)) #a陣列的長度為6
print(type(a)) #a陣列的類型




[2 9 5 6 5 8]
1
(6,)
6
int64
8
6
<class 'numpy.ndarray'>


In [4]:
b = np.random.randint(10, size=(3,4)) 

print(b.ndim) #b陣列有兩個軸
print(b.shape) #b陣列的形狀為3X4
print(b.size) #b陣列有12個元素
print(b.dtype) #b陣列的資料型態
print(b.itemsize) #b陣列每個元素的記憶體使用量
print(len(b)) #b陣列的長度為3
print(type(b)) #b陣列的類型

[[4 0 3 7]
 [7 8 6 0]
 [7 8 2 6]]
2
(3, 4)
12
int64
8
3
<class 'numpy.ndarray'>


In [6]:
c = np.random.randint(10, size=(2,3,2)) 

print(c)
print(c.ndim) #c陣列有3個軸
print(c.shape) #c陣列的形狀為(2,3,2)
print(c.size) #c陣列有12個元素
print(c.dtype) #c陣列的資料型態
print(c.itemsize) #c陣列每個元素的記憶體使用量
print(len(c)) #c陣列的長度為2，長度只會看最外層的維度，所以是2個4X3的陣列
print(type(c)) #c陣列的類型

[[[0 4]
  [5 1]
  [5 1]]

 [[2 4]
  [1 7]
  [0 2]]]
3
(2, 3, 2)
12
int64
8
2
<class 'numpy.ndarray'>


In [11]:
#6.如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。

a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 

def tolist (a):
    a_list = []
    if a.ndim == 1:
        a_list = list(a)
    if a.ndim == 2:
        for i in a:
            a_list.append(list(i))
    if a.ndim == 3:
        for i in a:
            for j in i:
                a_list.append(list(j))
    return a_list

print(tolist(a))
print(tolist(b))
print(tolist(c))

[5, 1, 1, 6, 9, 9]
[[5, 6, 8, 7], [9, 0, 3, 6], [1, 5, 4, 4]]
[[3, 3], [2, 8], [8, 3], [2, 0], [4, 7], [8, 9]]
